# https://docs.coderabbit.ai/guides/configure-coderabbit
language: "en-US"
early_access: false
chat: { auto_reply: true }
tone_instructions: >-
  Maintain a formal tone, highlighting issues, and suggesting production-grade, elegant, and concise solutions.

reviews:
  profile: chill
  high_level_summary: true

  poem: false

  collapse_walkthrough: true
  sequence_diagrams: true

  # File exclusions
  path_filters:
    - "**/*"
    - "!**/vendor/**"
    - "!**/bin/**"
    - "!**/build/**"
    - "!**/dist/**"
    - "!**/.git/**"
    - "!**/coverage.out"
    - "!**/coverage/**"
    - "!**/*.pb.go"
    - "!**/*_gen.go"
    - "!**/*.gen.go"
    - "!**/mock_*.go"
    - "!**/*_mock.go"

  path_instructions:
    - path: '**/*.go'
      instructions: >-
        Review the Go code, point out issues relative to principles of clean
        code, expressiveness, and performance.
    - path: '**/*.sh'
      instructions: >-
        Review the shell scripts, point out issues relative to security,
        performance, and maintainability.

  auto_review:
    drafts: false
    # disables review for new commits
    auto_incremental_review: false
    base_branches:
      - main

  tools:
    languagetool:
      enabled: true
      level: default
