name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      # Define Go variables
      GITHUB_GO_VERSION: '1.24'
      MODULE_PATH: github.com/speedrun-hq/speedrun-fulfiller
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GITHUB_GO_VERSION }}
        cache: true
    
    - name: Debug environment
      run: |
        go env
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "MODULE_PATH: $MODULE_PATH"
        pwd
        ls -la
    
    - name: Set up module replacement
      run: |
        # Add a replace directive to go.mod that points to the current directory
        # This lets Go know that imports of your module should resolve to this directory
        # regardless of where it's physically located
        echo "replace $MODULE_PATH => $(pwd)" >> go.mod
        cat go.mod

    - name: Install dependencies
      run: |
        go mod download
        go mod tidy

    - name: Build
      run: |
        go build -v ./...

    - name: Run tests
      run: |
        go test -v ./... -race 