name: CI

on:
  push:
    branches: [ main, fulfiller-improvements ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Verify directory structure
      run: |
        pwd
        ls -la
        ls -la pkg/fulfiller
        
    - name: Run isolated tests
      run: |
        go mod tidy
        make test-isolated
        
    - name: Verify build
      run: |
        go build ./... 