name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up module replacements
      run: |
        # Create a temporary module
        mkdir -p /tmp/builder
        cd /tmp/builder
        go mod init builder
        
        # Add the main module as a dependency with local replacement
        echo "require github.com/speedrun-hq/speedrun-fulfiller v0.0.0" >> go.mod
        echo "replace github.com/speedrun-hq/speedrun-fulfiller => $GITHUB_WORKSPACE" >> go.mod
        
        # Create a simple main.go that imports the module
        cat > main.go << 'EOF'
        package main
        
        import (
          _ "github.com/speedrun-hq/speedrun-fulfiller/pkg/fulfiller"
        )
        
        func main() {
          // Just import check
        }
        EOF
        
        # Build to verify
        go build
        
    - name: Run isolated tests
      run: |
        cd $GITHUB_WORKSPACE
        go mod tidy
        make test-isolated
        
    - name: Verify build
      run: |
        cd $GITHUB_WORKSPACE
        go build ./... 