name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: src

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Prepare workspace
      run: |
        mkdir -p $GITHUB_WORKSPACE/pkg/fulfiller
        cp -r src/pkg/fulfiller/* $GITHUB_WORKSPACE/pkg/fulfiller/
        cp src/go.mod src/go.sum $GITHUB_WORKSPACE/
        cp src/main.go $GITHUB_WORKSPACE/
        ls -la $GITHUB_WORKSPACE/pkg/fulfiller/
        
    - name: Run isolated tests
      run: |
        cd $GITHUB_WORKSPACE
        go mod tidy
        make test-isolated
        
    - name: Verify build
      run: |
        cd $GITHUB_WORKSPACE
        go build ./... 