name: CI

on:
  push:
    branches: [ main, fulfiller-improvements ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Create temporary module for building
      run: |
        # Create a temporary directory
        mkdir -p /tmp/builder
        cd /tmp/builder
        
        # Initialize a new module
        go mod init builder
        
        # Add the main module as a dependency with local replacement
        echo "require github.com/speedrun-hq/speedrun-fulfiller v0.0.0" >> go.mod
        echo "replace github.com/speedrun-hq/speedrun-fulfiller => $GITHUB_WORKSPACE" >> go.mod
        
        # Create a simple main.go that imports the module
        cat > main.go << 'EOF'
        package main
        
        import (
          _ "github.com/speedrun-hq/speedrun-fulfiller/pkg/fulfiller"
        )
        
        func main() {
          // Just import check
        }
        EOF
        
        # Build to verify
        go build

    - name: Verify main repo builds
      run: |
        cd $GITHUB_WORKSPACE
        go mod tidy
        go build ./... 