name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Create temporary module
      run: |
        # Create a simple module that just imports the main package
        mkdir -p /tmp/builder
        cd /tmp/builder
        cat > main.go <<EOF
        package main
        
        import (
          _ "github.com/speedrun-hq/speedrun-fulfiller"
        )
        
        func main() {}
        EOF
        
        go mod init builder
        go mod edit -replace github.com/speedrun-hq/speedrun-fulfiller=$GITHUB_WORKSPACE
        cat go.mod
        
        # Build should verify the module works
        go build -v

    - name: Verify main repo builds
      run: |
        cd $GITHUB_WORKSPACE
        go build -v 