name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: speedrun-fulfiller

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true

    - name: Setup Go module path
      run: |
        mkdir -p $GITHUB_WORKSPACE/github.com/speedrun-hq
        mv $GITHUB_WORKSPACE/speedrun-fulfiller $GITHUB_WORKSPACE/github.com/speedrun-hq/
        echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

    - name: Display Go environment
      run: |
        cd $GITHUB_WORKSPACE/github.com/speedrun-hq/speedrun-fulfiller
        go env

    - name: Install dependencies
      run: |
        cd $GITHUB_WORKSPACE/github.com/speedrun-hq/speedrun-fulfiller
        go mod download

    - name: Verify dependencies
      run: |
        cd $GITHUB_WORKSPACE/github.com/speedrun-hq/speedrun-fulfiller
        go mod verify

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/github.com/speedrun-hq/speedrun-fulfiller
        go build -v ./...

    - name: Run tests
      run: |
        cd $GITHUB_WORKSPACE/github.com/speedrun-hq/speedrun-fulfiller
        go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic 