name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Fix memsize package
      run: |
        go get github.com/fjl/memsize@v0.0.0-20190710130421-bcb5799ab5e5
        go mod tidy
        
    - name: Run isolated tests
      run: |
        make test-isolated
        
    - name: Verify build
      run: |
        go build ./... 