name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true

    - name: Fix dependencies
      run: |
        go mod tidy

    - name: Run isolated tests
      run: |
        # Run only the standalone isolated tests that don't depend on go-ethereum
        go test -v ./pkg/fulfiller/approval_test.go ./pkg/fulfiller/simple_test.go ./pkg/fulfiller/isolated_test.go

    - name: Run test with coverage
      run: |
        # Generate coverage report for isolated tests
        go test -v -coverprofile=coverage.out ./pkg/fulfiller/approval_test.go ./pkg/fulfiller/simple_test.go ./pkg/fulfiller/isolated_test.go

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        flags: unittests
        verbose: true 