name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true

    - name: Set up module path
      run: |
        # Create the correct module structure
        mkdir -p $GITHUB_WORKSPACE/src/github.com/speedrun-hq/
        ln -s $GITHUB_WORKSPACE $GITHUB_WORKSPACE/src/github.com/speedrun-hq/fulfiller
        echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "GO111MODULE=on" >> $GITHUB_ENV

    - name: Setup and run tests
      run: |
        # Use our Makefile targets
        make setup
        make test-isolated